-- CreateTable
CREATE TABLE `conversion_credits` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `credit` INTEGER NOT NULL,
    `prix` DECIMAL(10, 2) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
